version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    target-branch: "main"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps)"
      # Prefix for all commit messages that update dependencies in the Development dependency group
      prefix-development: "chore(deps-dev)"
